### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by baua1310** [Cyberbyte-Studios/CyberWorks#10]
I have set up the Panel three times and everytime I get this error:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

the url is www.take-two-roleplay.de/webpanel/

**Comment by MightySCollins** [comment]
Sorry for the delay in replying, I though I already had but it didn't send. Can I see your .htaccess file?

**Comment by baua1310** [comment]
No problem, here is my .htaccess file:

RewriteEngine On
RewriteBase /webpanel/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /webpanel/index.php [L]

php_value file_get_contents 1

**Comment by MightySCollins** [comment]
Hmm it all looks like it should, is it on a shared host?

**Comment by baua1310** [comment]
Yes it is on [NGZ](https://www.ngz-server.de/en/)

**Comment by MightySCollins** [comment]
Hmm I am not really sure, can you send me the last few errors in the error log?

**Comment by baua1310** [comment]
No I'm sorry. I haven't access to the server logs but the support told me, it has something to do with 'php_value file_get_contents 1'. So I deleted it and now it works :)

**Comment by MightySCollins** [comment]
Ok well thats great, I am not sure why it is not working for you. Any other problems open a issue ;)
