### ISSUE TITLE
Change Mysql Port

### ISSUE THREAD

**Issue by Gotteshand** [Cyberbyte-Studios/CyberWorks#11]
Hi All.

I I have a Big Problem. 

My MySQL has a different port 3307. I am assuming that the installtion via the 3306 port goes. Where or how can I change that I get CyberWorks installed?

Many thanks

**Comment by MightySCollins** [comment]
That should be no problem, you can try using `127.0.0.1:3307` in the IP feild and it should work it out

**Comment by Gotteshand** [comment]
Hello. I now have the port specified during installation with and get this error:
Connect failed: Unknown MySQL server host '94.250.222.8:3307' (74) 
This I have registered with SQL host.

Big Thx for Help

**Comment by Gotteshand** [comment]
Hello. I have to be able to still do not perform the installation problem. Even if I enter the IP + 3307 I get an error message.

Connect failed: Unknown MySQL server host '94.250.222.8:3307' (74) 
Would be great if someone could help me.

**Comment by MightySCollins** [comment]
Ahh it seems we have overlooked something in the port support. Unfortunately I am currently working on Cyberworks 2 and have not looked at this code in a while, if you look in `firsttime.php` you should be able to temporarily hard code your details in. Sorry I cannot be of any more help but I will quickly look into it soon
