### ISSUE TITLE
Staff Code Error 

### ISSUE THREAD

**Issue by DJTrb96** [Cyberbyte-Studios/CyberWorks#12]
Hello Guys, 

I've gotten a SQL Error in staff? I guess it's an error. Heres a screenshot of it. 

http://i.imgur.com/X9GLDTS.png

The Red colour is just over our emails, 

I googled a some of the "error" code into google and found a pastebin with the exact same issue. 

Can be found here: http://pastebin.com/WT54VJXu 

Any idea on how to fix it? Cheers

**Comment by MightySCollins** [comment]
Hey

Download the latest master or remove our var_dump from views/core/staff.php
it's near the top.

Sorry about that
Sam

**Comment by DJTrb96** [comment]
Hello Sam, 

I removed the following 

"ar_dump($_SESSION);
$max = ' LIMIT ' . ($pageNum - 1) \* $_SESSION['items'] . ',' . $_SESSION['items'];

if (isset($search)) {
    logAction($_SESSION['user_name'], $lang['searched'] . ' (' . $search . ') ' . $lang['in'] . ' ' . $lang['staff'], 3);

```
$sql = "SELECT * FROM `users` WHERE `user_name` LIKE '" . $search . "' OR `user_email` LIKE '" . $search . "' OR `user_id` LIKE '" . $search . "' OR `playerid` LIKE '" . $search . "';";
$result_of_query = $db_connection->query($sql);
$total_records = mysqli_num_rows($result_of_query);
$sql = "SELECT * FROM `users` WHERE `user_name` LIKE '" . $search . "' OR `user_email` LIKE '" . $search . "' OR `user_id` LIKE '" . $search . "' OR `playerid` LIKE '" . $search . "'" . $max . " ;";
```

} else {
    $sql = "SELECT count(`user_id`) FROM `users`;";
    $total_records = $db_connection->query($sql);
    $sql = "SELECT \* FROM `users` " . $max . " ;";
}
" 

Is this what you mean? 

Now we can't see anything in the staff section. Sorry i'm not the smartest with this! 

Cheers Tom

**Comment by MightySCollins** [comment]
Hi,

No thats fine its was just line 2 which had the `var_dump` in. If you have already deleted it then just make sure it looks like this, https://raw.githubusercontent.com/Cyberbyte-Studios/CyberWorks/master/views/core/staff.php

Sam

**Comment by DJTrb96** [comment]
Hello Thank you very much Sam. This worked perfectly, i just had another question do you support modification / editing around a few things. I just wanted to play around with it as a personal project.

**Comment by MightySCollins** [comment]
Yes that's fine just be sure to credit us ;)
Enjoy and good luck
