### ISSUE TITLE
failed to open stream: HTTP request failed! 

### ISSUE THREAD

**Issue by shizotheone** [Cyberbyte-Studios/CyberWorks#13]
Warning: file_get_contents(http://cyberbyte.org.uk/hooks/cyberworks/getid.php?url=http://localhost/supp/&name=Avanix%20Gaming&pid=): failed to open stream: HTTP request failed! in C:\xampp\htdocs\supp\views\firstTime.php on line 39

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\supp\views\firstTime.php on line 39

**Comment by MightySCollins** [comment]
We are actively fixing this issue

**Comment by shizotheone** [comment]
Okay thanks

Von meinem iPhone gesendet

**Comment by Mateeox** [comment]
I have same error msg :| 
I can't wait patch :)

**Comment by MightySCollins** [comment]
Ok so there have been too many emails for me to ignore, http://www.altisliferpg.com/topic/11209-php-tool-cyberworks-altis-life-admin-panel/?p=78654

**Comment by MightySCollins** [comment]
Ok committed a simple fix can someone test it for me by pulling the latest master

**Comment by Mateeox** [comment]
It works for me ;) Thank you!

**Comment by Mateeox** [comment]
However now I get error when I'm trying to login: 
Warning: file_get_contents(http://cyberbyte.org.uk/hooks/cyberworks/messages.php?id=1001): failed to open stream: HTTP request failed! in C:\xampp\htdocs\forum\panel\classes\login.php on line 107

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\forum\panel\classes\login.php on line 107

**Comment by cammygames** [comment]
Should be fixed now
