### ISSUE TITLE
Cyberworks 2

### ISSUE THREAD

**Issue by trdwll** [Cyberbyte-Studios/CyberWorks#14]
I'm curious when you're going to open source Cyberworks 2.

**Comment by MightySCollins** [comment]
Hmm good question, we are not really sure...
Although we feel it would benefit many more communities as it is a much better panel it is also much harder to install and setup leaving it out of the question for smaller communities. We will consider it soon but we are currently just polishing off the last sections of it to make it a very stable release if we do it.

**Comment by trdwll** [comment]
Good to know. 
Also, please tell me you're using OOP on the new version and I'd be down to assist in the development of it either after you release it or before.

**Comment by MightySCollins** [comment]
Of course, it has been completely redone in Laravel and most of it seems to follow programming standards, I got sick of looking at the old messy code which was not even using PDO and converting it all and changing it was WAY to much work. Send me an email at theatrepro11@gmail.com.
