### ISSUE TITLE
Missing editwanted

### ISSUE THREAD

**Issue by Provokan** [Cyberbyte-Studios/CyberWorks#15]
We miss for the 4.0 the wanted page :/

**Comment by MightySCollins** [comment]
You are welcome to port it over ;)

**Comment by Provokan** [comment]
LoL, then why are the cornerstones already been set for it? xD After all, in the editplayer.php button /editwanted.php deposited!

**Comment by MightySCollins** [comment]
Because we have already written it... But I guess we did not include it due to a bug

**Comment by Provokan** [comment]
give me the.php files i fill fixx the problem and send u the bag (:
