### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ThoronadNg** [Cyberbyte-Studios/CyberWorks#18]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
- PHP-5.4
  what else do you need to know?

**Comment by MightySCollins** [comment]
Would be nice if we could see the server log, any php errors?
Where this problem was and what you did to get it would help.
Also see http://php.net/supported-versions.php for details about PHP 5.4

**Comment by ThoronadNg** [comment]
[Sun Jan 10 17:18:56 2016] [alert] [client 130.193.xx.xx] /var/www/web462/html/lastshelter/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration
[Sun Jan 10 17:18:57 2016] [alert] [client 130.193.xx.xx] /var/www/web462/html/lastshelter/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration
[Sun Jan 10 17:53:48 2016] [error] [client 95.223.xx.xx] Script timed out before returning headers: index.php, referer: http://xoxoxox.org/lastshelter/
[Sun Jan 10 17:53:48 2016] [error] [client 95.223.xx.xx] PHP Warning:  file_get_contents(http://cyberbyte.org.uk/hooks/cyberworks/getid.php?url=http://xoxoxox.org/lastshelter/&amp;name=Last%20Shelter%20Multigaming%20Community&amp;pid=): failed to open stream: HTTP request failed!  in /var/www/web462/html/lastshelter/views/firstTime.php on line 39, referer: http://xoxoxox.org/lastshelter/

**Comment by ThoronadNg** [comment]
Changed PHP version to 7.0 problem still present

**Comment by MightySCollins** [comment]
Hi

Is this on your own server or shared hosting, all of these issues are most likely down to server configuration. If your .htaccess does not support setting PHP Values then you can remove them from the file and change them on your php.ini file. Also make sure you have the latest version from master not the release, we will be doing a new release soon.

We have not yet tried it out with PHP7, so tell us how well it work.

Sam

**Comment by Felix2** [comment]
I got the same error at first. Try remove this line from the htaccess

php_value file_get_contents 1

If that dont do it u need to make sure u have the correct permission set. 755

**Comment by Thiritin** [comment]
@Felix2 Yeah i did this too, after looking in the Error logs.
