### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CrackH34D** [Cyberbyte-Studios/CyberWorks#19]
hey, 

we always get the error:

Not Found

The requested URL /index was not found on this server.

after login

wot can we do?

**Comment by Provokan** [comment]
Crackhead, 

u need to write a htacces. on your webspace for working the webpage (:

**Comment by MightySCollins** [comment]
@Provokan Yep, thanks for that, make sure our setup made it for you. If it did not you can try using

```
RewriteEngine On
RewriteBase /<FILE PATH FROM ROOT URL>
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /<FILE PATH FROM ROOT URL>index.php [L]
php_value file_get_contents 1
```

**Comment by Provokan** [comment]
Crackhead, when u need help for the panel. And u are a German Player, u can add me on steam ounder twinhead130

**Comment by MightySCollins** [comment]
Is this fixed?

**Comment by Provokan** [comment]
its works (: i host his panel on my webspace

**Comment by StealthyGazer** [comment]
@Provokan Hey man - I am getting the same error. Any help would be appreciated <3

**Comment by StealthyGazer** [comment]
@MightySCollins

**Comment by MightySCollins** [comment]
@DarkSilencerZA This is a user install error, please ensure that the .htaccess is correctly generated you are on an Apache server and mod_rewrite is on. If this is all true then please tell me the url of the install. if you would prefer you can send me a PM on the forums with it

**Comment by StealthyGazer** [comment]
@MightySCollins Hi there! Thanks for your response. Are you able to send me the correct .htaccess for your build? I will update accordingly and change the file paths.

**Comment by MightySCollins** [comment]
It should auto generate one, to make one manually I will need to know the
install url.

**Comment by Felix2** [comment]
I got a interna server error after install so i removed this line:

php_value file_get_contents 1

Now it works for me.

**Comment by philizz** [comment]
Same problem.
I´m running on windows server 2012.
Can you please help me?

**Comment by MightySCollins** [comment]
@philizz Hi,
Are you running ISS? Also can we do this in a new issue this should be closed.
