### ISSUE TITLE
#Kick function doesn work

### ISSUE THREAD

**Issue by Provokan** [Cyberbyte-Studios/CyberWorks#20]
Hello Together,

the kick function, doesn work. He connect to the Server but dont kick one player

**Comment by MightySCollins** [comment]
Hi,

Thanks for this at some point we need to rewrite the RCON class, just to confirm are you able to see players? Is there anything outputted to the JS console and what PHP version are you using?

Thanks for the bug report I will look into it soon.

**Comment by Provokan** [comment]
I can see the Players, i can send one Globale Message and can use the Execute (alias loadScripts,MaxPing,say, #mission, addBan, ban, removeBan >

php 5.6

**Comment by MightySCollins** [comment]
If you use chrome devtools and look at the network section do you see a request that is going to rcon_click? If you do can you give me the response

**Comment by Provokan** [comment]
http://prntscr.com/9pseg4

**Comment by Provokan** [comment]
I suspect that the kick button, the Lot number of the player can not find it and therefore not working

**Comment by MightySCollins** [comment]
Hmm it needs to provide both the sid(Server ID) and the id(Player ID), and you just see if that code has been added to the buttons in the html?

**Comment by Provokan** [comment]
Response 
["0","_FOR SAFETY IP_","16","1455a1bce1ea8d88d66243ae54f4659b(OK)","[MoD]","Ole","Doom"],["1","FOR SAFETY IP_","15","0364d12e7b0cf1950abfb52686d1bb11(OK)","[ING]","Fettarme","Milch"],["2","FOR SAFETY IP_","16","b64dc85055f27e5eea0a0a95ed6881e8(OK)","[MoD]Disturbed","Doom"],["3","FOR SAFETY IP_","16","f5955b646ef62030d0dfd2a2cbea9a89(OK)","[MoD]","Taipan","Doom"],["7","FOR SAFETY IP_","16","93bb6f97085c4febd1528d362384bdd2(OK)","Pascal","Fame"]

Preview

["0", "FOR SAFETY IP_", "16", "1455a1bce1ea8d88d66243ae54f4659b(OK)", "[MoD]", "Ole", "Doom"]
1: ["1", "FOR SAFETY IP_", "15", "0364d12e7b0cf1950abfb52686d1bb11(OK)", "[ING]", "Fettarme",
2: ["2", "FOR SAFETY IP_", "16", "b64dc85055f27e5eea0a0a95ed6881e8(OK)", "[MoD]Disturbed", "Doom"]
3: ["3", "FOR SAFETY IP_", "16", "f5955b646ef62030d0dfd2a2cbea9a89(OK)", "[MoD]", "Taipan", "Doom"]
4: ["7", "FOR SAFETY IP*", "16", "93bb6f97085c4febd1528d362384bdd2(OK)", "Pascal", "Fame"]

i find the problem, the kick button doesn talk to the PID

**Comment by MightySCollins** [comment]
I remember now that we made sure this did not work just in case as we did not think it was very secure. We will see if we can get it working on CyberWorks 2
