### ISSUE TITLE
The requested URL /arma3server/index was not found on this server.

### ISSUE THREAD

**Issue by anndrox** [Cyberbyte-Studios/CyberWorks#21]
I put everything in my root directory and everything and still I cannot log in. I filled out all the information and it brings me here and then I put .php at the end and it gives me a login page. I log in and same thing... I'm confused!  http://playongaming.net/arma3server/index

**Comment by MightySCollins** [comment]
Can we see your `.htaccess` file?
Also when  you say root do you mean http://playongaming.net/ or http://playongaming.net/arma3server/

**Comment by anndrox** [comment]
RewriteEngine On
RewriteBase /arma3server/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /arma3server/index.php [L]

php_value file_get_contents 1

also here is my php info http://playongaming.net/test.php

I unzipped in my dir and I also had to change chmod to give it write access, otherwise it would bring me to the setup page every time. Right now its playongaming.net/arma3server and when I try to log in, it does the same thing. Let me know if you need more information. I am running ubunto 15.10

ps. "Can we see your .htaccess file?" It sounds like something you ask a chick when you're drunk ;p

**Comment by MightySCollins** [comment]
I assume this is a server you setup yourself so I think you missed a step. Almost all sites running Apache need mod_rewrite. Try running `sudo a2enmod rewrite` to enable the apache rewrite module so it can handle requests correctly on your server.

**Comment by anndrox** [comment]
Okay. I reenabled it and restarted apache2 and I'm still getting same results.
Here are my apache2 syslogs
http://pastebin.com/pJ5Ybx8C

**Comment by Thiritin** [comment]
I do have the same problem and i run it at a root directory you can try if you want: http://novacontrol.cf, now i try to reinstall it without a domain.

**Comment by MitzelLP** [comment]
Do you use OVH and/or Cloudflare?

**Comment by anndrox** [comment]
I have kimsufi as a provider which is owned by OVH

**Comment by Thiritin** [comment]
I want to try something i think it may something with ovh. can i speak to you http://steamcommunity.com/id/Martin_Becker

I got it running and i think i know the problem.

Look at this http://37.187.243.250/arma/ try to login with any account and any password.

Edit: Tried to install it on a different Server in a different country. Still the same Error.
Could someone please send us their vhost for apache2?

**Comment by anndrox** [comment]
I'm still getting same error with that page also. Sent request from c0ba7t on http://steamcommunity.com/id/anndrox/home/

**Comment by MightySCollins** [comment]
It is not an OVH error but a server configuration error, Have you allowed overrides by a .htaccess file for the directory you are using also @anndrox I think I know your problem, the files are in the folder `Cyberworks` but the url is `arma3server` try renaming Cyberworks to be `arma3server` as our .htaccess generator has been confused.

**Comment by anndrox** [comment]
I have installing/reinstalling it so that's why it's not there anymore. With each install I make sure the htaccess is pointing to the correct directory. I will try the htaccess overrides when I get home

**Comment by MightySCollins** [comment]
Did you have any luck with this?

**Comment by MightySCollins** [comment]
Is there any more to this or can I close it?

**Comment by Provokan** [comment]
u can close it (:
