### ISSUE TITLE
Notice: Trying to get property of non-object in

### ISSUE THREAD

**Issue by Provokan** [Cyberbyte-Studios/CyberWorks#22]
i cant fixx the problem, u cant find the problem?!

Notice: Trying to get property of non-object in /var/customers/webs/ni434908_1/hawaii/views/life/vehicles.php on line 26  no License

http://pastebin.com/wDb9qtsp

**Comment by MightySCollins** [comment]
Hmm, sorry for late reply this slipped through my inbox.

It would see, that is due to our rubbish code if there is no successful query then there can be no row numbers! Try adding an if isset above and running the queries on the database to see if they work.

**Comment by Provokan** [comment]
its working, i fixxing the problem, all come with the next big push from me

**Comment by MightySCollins** [comment]
Ok nice ;)
