### ISSUE TITLE
Server Query - No connection?

### ISSUE THREAD

**Issue by CyberSecGuy** [Cyberbyte-Studios/CyberWorks#26]
I'm running my webserver on localhost, as well as my arma 3 server on localhost.

Using EPM Rcon Tool I'm able to RCON into my server via external ip, network ip, and localhost on 2302 using the password, however when I attempt to add my server to the CyberWorks panel, and I specify the exact same settings, it continues to refresh every 30 seconds, and doesn't show any players. Additionally it's not sending messages from the "Say" box.

How can I fix this?

**Comment by MightySCollins** [comment]
What version of PHP are you using? This feature seems to only work on certain environments.

**Comment by CyberSecGuy** [comment]
arma3server@stream-MS-7576:~$ php -v
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)

**Comment by MightySCollins** [comment]
Sorry for the delay, are there any errors in the logs?

**Comment by CyberSecGuy** [comment]
I'm no longer involved in that project, so, I don't know what /my/ issue was, but it wouldn't connect via localhost/127.0.0.1  but it **DID** connect externally to an external server.

**Comment by MightySCollins** [comment]
Hmm, ok well thanks for saying RCON is held together with duck tape so often fails
