### ISSUE TITLE
issue: search is not work

### ISSUE THREAD

**Issue by HyunsukBaek** [Cyberbyte-Studios/CyberWorks#27]
in players tab(or page), search method is not working. 
and, how to ban player? ?

**Comment by MightySCollins** [comment]
Hi, Do you have any more details?
What's is the problem with it and is it giving you any errors?
Also banning by button was removed, you can type in the command manually into the RCON box and run it.

**Comment by HyunsukBaek** [comment]
@MightySCollins   search is correctly working, my mistake is - put search keyword in textfield and then i push enter key,  not search button.   

it's not an issue. close plz. 
ps : when user put enter key in search text field, id like to go run search method

**Comment by MightySCollins** [comment]
hmm I though it did submit on enter, ohh well
