### ISSUE TITLE
Refers me to a non existing page.

### ISSUE THREAD

**Issue by andrew77768** [Cyberbyte-Studios/CyberWorks#28]
I've tried emailing Cammy but I'm suffering with problems from my Email Provider so my best bet is to ask here.

I think I have made an error while installing this but when I am attempting to install this using the installer ( /AL/Index.php ) it will then refer me to a non existing page ( /AL/index?setup=1 ). 

This is the error I'm presented with:
 "Object not found! The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error. "

I read that I need to set up a .HTACCESS file but I don't know where to start as I'm new to the general website developing thing. 
Any help is appreciated, I love the look of the panel! 

Thanks

**Comment by MightySCollins** [comment]
Try using `/AL/index.php` with a lowercase URL I think setup is case sensitive

**Comment by andrew77768** [comment]
That didn't work so I found a tutorial to install a different one and used it for this and it worked.
The guy changed his .HTAccess to this: 

<Files />
RewriteEngineOn
RewriteBase /AL/
RewriteCond %{REQUEST_FILENAME}!-f
RewriteRule . /AL/index.php
php_value file_get_contents 1
</Files>

and it worked for me too. 

Thanks <3

**Comment by MightySCollins** [comment]
Any chance you can post a link, it might help others ;)
