### ISSUE TITLE
Removing 2 factor authentication

### ISSUE THREAD

**Issue by Felix2** [Cyberbyte-Studios/CyberWorks#29]
I have tried to remove it after accidently enabling it but when pressing the revoke button it forces you to do it again.

Also it seems having 2factor enabled makes the mobile version useless since its not possible to enter the code or view any page.

Which file do i edit to disable it?

**Comment by Felix2** [comment]
I have tried to remove it after accidently enabling it but when pressinformatör the revoke button it forces you to do it again.

Also it seems having 2factor enabled makes the mobile version useless since its not possible to enter the code or view any page.

**Comment by Felix2** [comment]
Which file do i edit to disable it?

**Comment by MightySCollins** [comment]
Have you setup 2 Factor with your phone and can you login?

**Comment by Felix2** [comment]
Yes. But once the 2 factor has been turned on in the settings its not possible to turn it off.

**Comment by MightySCollins** [comment]
And does the option in settings not work?

**Comment by Felix2** [comment]
No, It's not possible to turn it off from there.

**Comment by MightySCollins** [comment]
Does the option not work? https://github.com/Cyberbyte-Studios/CyberWorks/blob/master/views/core/settings.php#L169

If not its the 2factor option in the settings DB I think

**Comment by Felix2** [comment]
Look at this detailed image: 
http://i.imgur.com/sFmytih.png

Also, what part do I edit in the DB?

**Comment by MightySCollins** [comment]
Although this has been fixed in the next update by @cammygames you can change `2factor` to false in `/config/settings.php` not in the DB sorry.

**Comment by Thiritin** [comment]
Hmm if this dosent work you can remove the 2factor php file :-).

Waiting for the next Update :-)

**Comment by cammygames** [comment]
2Factor is disabled in the next update

**Comment by MightySCollins** [comment]
This has now been fully removed in f7aa577caec8470007c11bd623bd0fad33f10cb3
