### ISSUE TITLE
Logging how much money has been added

### ISSUE THREAD

**Issue by Felix2** [Cyberbyte-Studios/CyberWorks#30]
I'm trying to see how much money has been added from a moderator to a player in the logs but all I can see is: "Edited User(76561111111111111) Levels"

Is it possible to see how much money has been added?

It would be very nice if it displayed a detailed log like this:
"Edited User(76561111111111111) Bank 50.000 --> 100.000"
or
"Edited User(76561111111111111) Cash 50.000 --> 100.000"

**Comment by Felix2** [comment]
In my opinion this is the only thing missing for this cool control panel.

Knowing how much Cash / Bank money has been added is very important to know.

**Comment by cammygames** [comment]
like this http://puu.sh/nMfk8/2ef26c0564.png

**Comment by Felix2** [comment]
Exactly like that! :)

**Comment by cammygames** [comment]
it was there all along it just wasn't working apparently. it will be fixed and pushed out by the end of today

**Comment by Felix2** [comment]
When is the update coming ?

**Comment by cammygames** [comment]
Sorry we have been working on a support system for cyberworks. ill try to have it out by this evening

**Comment by Felix2** [comment]
Alright, cool!

**Comment by MightySCollins** [comment]
f7aa577caec8470007c11bd623bd0fad33f10cb3 just went out with the changes in, please tell me if it all works :smile:
