### ISSUE TITLE
Please update installation instructions

### ISSUE THREAD

**Issue by marrold** [Cyberbyte-Studios/CyberWorks#33]
The instructions are a little vague. To get this working on Ubuntu I had to do the following -

install php5-mysql php5-mcrypt
sudo php5enmod mcrypt

Additionally on the dashboard I get the error-

Notice: Undefined variable: verify in /var/www/html/classes/login.php on line 124

Thanks

**Comment by MightySCollins** [comment]
I'll be honest we do expect all users to have a basic Apache setup, there are a few common modules which are required by almost all PHP projects, another one you might need is `mod_rewrite`. Ill try and add it somewhere soon.
