### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ZeroGood** [Cyberbyte-Studios/CyberWorks#38]
Hello there !

I have some problems to login.. when i try i have a error 404 "URL not found"

here my HTaccess : 

RewriteEngine On
RewriteBase /admin/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /admin/index.php [L]
php_value file_get_contents 1

Thanks a lot for your help !
Regards,

**Comment by ZeroGood** [comment]
problem resolved in apache2.conf :)

**Comment by MightySCollins** [comment]
What did you do to fix it?

**Comment by Thiritin** [comment]
I have the same problem, it works on my webhoster but not at my personal, please share the fix to the others, would be awesome.

**Comment by ZeroGood** [comment]
Hello ! 
Try to put this on your apache2.conf (don't forget to change the path of your webpanel) : 

```
<Directory /var/yourpath/>
        Options Indexes FollowSymLinks
         AllowOverride All
         RewriteEngine On
         Require all granted
</Directory>
```

my .htaccess 

```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L]
```

and restart apache ;)
+

**Comment by Thiritin** [comment]
Thank you I will try it. :-)
