### ISSUE TITLE
Translate to french

### ISSUE THREAD

**Issue by ZeroGood** [Cyberbyte-Studios/CyberWorks#39]
Hello there ! 
I want made the translation in french for a community and share it here.

But i need some help to locate every files to do it. Can you help me ? :)

+

**Comment by MightySCollins** [comment]
Hey sorry for the delay, just fork this file https://github.com/Cyberbyte-Studios/CyberWorks/blob/master/config/english.php and add in french and I can sort the rest.

**Comment by ZeroGood** [comment]
done ;)
I will improve this version when i can see the result on a active page !

**Comment by BoGuu** [comment]
Any news?
