### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by normanaluk** [Cyberbyte-Studios/CyberWorks#40]
Hey I have a problem with cyberworks

I set it up on my dedicated web server but it doesn't work, the circle just spins around and the page times out. (http://blackshadow.co.uk/arma)

I tried it on http://inviz.io and it worked made me an account but I don't know where to login?

Please help

**Comment by MightySCollins** [comment]
Hi

Sorry for the delay, we are slowly rolling out a new support ticket system on our new website. If you can make a ticket https://cyberbyte.org.uk/support/ in the Cyberworks category we should get back to you quickly.

Thanks
Sam
