### ISSUE TITLE
4.4 Support for the players table

### ISSUE THREAD

**Issue by Felix2** [Cyberbyte-Studios/CyberWorks#41]
It doesn't seem to work on Altis Life 4.4r2. I have tested 4 different versions of cyberworks and none of them I was able to edit Bank, Cash, Coplevel, Adminlevel, Mediclevel.

The other functions seemed to work though.

Does this have something to do with that the database structure has been changed for the players table?

**Comment by BoGuu** [comment]
I'll look into changing the DB structure to match the new columns

**Comment by Felix2** [comment]
Cheers :)

**Comment by Felix2** [comment]
@BoGuu Thank you, it's working now again :)
