### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by niconowy** [Cyberbyte-Studios/CyberWorks#43]
Hello.

Always i get the Error: HTTP Error 500.
How can i fix it?

Error Log:
[Sun May 15 16:41:00 2016] [info] Loading certificate & private key of SSL-aware server
[Sun May 15 16:41:00 2016] [debug] ssl_engine_pphrase.c(470): unencrypted RSA private key - pass phrase not required
[Sun May 15 16:41:00 2016] [info] Configuring server for SSL protocol
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(465): Creating new SSL context (protocols: SSLv3, TLSv1)
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(673): Configuring permitted SSL ciphers [HIGH:MEDIUM:!ADH]
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(420): Configuring TLS extension handling
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(804): Configuring RSA server certificate
[Sun May 15 16:41:00 2016] [warn] RSA server certificate CommonName (CN) `Parallels Panel' does NOT match server name!?
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(843): Configuring RSA server private key
[Sun May 15 16:41:00 2016] [info] Loading certificate & private key of SSL-aware server
[Sun May 15 16:41:00 2016] [debug] ssl_engine_pphrase.c(470): unencrypted RSA private key - pass phrase not required
[Sun May 15 16:41:00 2016] [info] Configuring server for SSL protocol
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(465): Creating new SSL context (protocols: SSLv3, TLSv1)
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(673): Configuring permitted SSL ciphers [HIGH:MEDIUM:!ADH]
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(420): Configuring TLS extension handling
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(804): Configuring RSA server certificate
[Sun May 15 16:41:00 2016] [warn] RSA server certificate CommonName (CN)`Parallels Panel' does NOT match server name!?
[Sun May 15 16:41:00 2016] [debug] ssl_engine_init.c(843): Configuring RSA server private key
[Sun May 15 16:43:34 2016] [debug] mod_headers.c(743): headers: ap_headers_output_filter()
[Sun May 15 16:43:34 2016] [debug] mod_deflate.c(615): [client 217.230.60.191] Zlib: Compressed 0 to 2 : URL /index.php

**Comment by MightySCollins** [comment]
Hi

Sorry for the delay, we are slowly rolling out a new support ticket system on our new website. If you can make a ticket https://cyberbyte.org.uk/support/ in the Cyberworks category we should get back to you quickly.

Thanks
Sam
