### ISSUE TITLE
MySQL port

### ISSUE THREAD

**Issue by NickITGuy** [Cyberbyte-Studios/CyberWorks#44]
How do I make sure that the panel is trying to connect to a certain port because my server is running on 3307 not the default port.

**Comment by MightySCollins** [comment]
Hi

Sorry for the delay, we are slowly rolling out a new support ticket system on our new website. If you can make a ticket https://cyberbyte.org.uk/support/ in the Cyberworks category we should get back to you quickly.

Thanks
Sam

**Comment by BoGuu** [comment]
It's been months, closing. Please re post if you still experience any problems.
