### ISSUE TITLE
Server Query / RCon Port

### ISSUE THREAD

**Issue by StealthyGazer** [Cyberbyte-Studios/CyberWorks#48]
As of a recent update, RCon ports need to be defined. This means that you can no longer use the Server OR Server Query port for RCon connections. An extra option needs to be added to allow defining of both.

**Comment by BoGuu** [comment]
https://i.gyazo.com/0cb411204a3912a3d8304ce0122b55b1.png

https://i.gyazo.com/eaa1dc8a6bc8d7ba2a967ca808c7aee3.png

**Comment by BoGuu** [comment]
AFAIK only the RCon port is used, so if you put your RCon port into the server query port, it'll work regardless. Could be wrong though. If this is the case we can change the text to make it more explicit
