### ISSUE TITLE
Fix table names in update query for players

### ISSUE THREAD

**Issue by vbrandl** [Cyberbyte-Studios/CyberWorks#53]
In `/views/life/editPlayer.php` when updating a players data, you refer to the donator level column by `donorlevel` but it is called `donatorlvl` in the database. 
This way you cannot save the changes, because the update query fails.
To fix this, you need to change lines 73 and 97 in `/views/life/editPlayer.php` and replace `donorlevel` in the query by `donatorlvl`.

**Comment by MightySCollins** [comment]
We welcome any pull requests, this issue is because the Altis Life Framework updates and we do not have the time to keep up with changes.

**Comment by vbrandl** [comment]
done
https://github.com/Cyberbyte-Studios/CyberWorks/pull/55
