### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Valtropalis** [Cyberbyte-Studios/CyberWorks#6]
RewriteEngine On
RewriteBase /panel/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /panel/index.php [L]

php_value file_get_contents 1

host is linux database has been made. but i cant get on the panel.

**Comment by Valtropalis** [comment]
install url is www.thealtisproject.co.uk/panel

**Comment by MightySCollins** [comment]
Hmm it seems to be able to get on it ![screenshot_24](https://cloud.githubusercontent.com/assets/8594759/9654672/34add658-5224-11e5-91ea-174346e2007c.png)

**Comment by Valtropalis** [comment]
and when do we have exile support ?

**Comment by MightySCollins** [comment]
Well we do have exile support but our topic on the website was locked and it seems we cannot get hold of the admin which did it. Its nearly been completed but we stopped as we realized if we could not post on the forums we could not easily give it to people and offer support.
