### ISSUE TITLE
Database Write Issue?

### ISSUE THREAD

**Issue by xProlithium** [Cyberbyte-Studios/CyberWorks#61]
I've tried to fix it on my own but with no positive results. Whenever I try to edit something like a person's cop or civ level it doesn't take and stays the same. After looking through the database itself, it doesn't even show CyberWorks having an active connection with the database.

**Comment by xProlithium** [comment]
Until this issue is seen an addressed I've had to revert to the LifeControl 2.0

**Comment by cammygames** [comment]
Are you using the latest version from git, as this was patched a while ago via a pull request.

**Comment by xProlithium** [comment]
Is it the pull #42 that should be added to it? I'll give it a try.

Even after making the changes noted in pull #60 it still doesn't change information though the web panel.

**Comment by cammygames** [comment]
What life version are you using? 4.x or 3.x?

**Comment by xProlithium** [comment]
I was using CyberWorks 0.5, and it was reading information from the DB but not editing or writing to it. However the LifeControl 2.0 works fine using the same user.

**Comment by cammygames** [comment]
What Altis life version are you using though?

**Comment by xProlithium** [comment]
Our Altis Life version is 3.1.4.8.

**Comment by MightySCollins** [comment]
Ahh yes, it is possible some of our changes to accommodate the newer versions have broken compatibility. I will close this as we are no longer supporting older versions but thank you for reporting it.
