### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by matze3331** [Cyberbyte-Studios/CyberWorks#62]
Hey Guys,

first, great project you are working on! But, a user of mine installation requested to reset his password.
how do i do that? If i activate the password reset function, i get the warning...

What should I do?

**Comment by BoGuu** [comment]
Profile page?

**Comment by matze3331** [comment]
I want to reset HIS password not mine.

**Comment by MightySCollins** [comment]
Delete and remake the account...

I think we turned this off sorry

**Comment by matze3331** [comment]
Okay, thanks.
