### ISSUE TITLE
Altis Life 4.4r Issue 

### ISSUE THREAD

**Issue by llMysterioll** [Cyberbyte-Studios/CyberWorks#65]
I set the panel up with the exact info used when running extdb 2 and it still doesn't work. The web panel worked fine with me before. The odd part it shows the newest and richest players but when you attempt to view players nothing can be found.
![Player Not Found](https://i.gyazo.com/90e877e812b1a7cecef215270d1c18eb.png)
![Dashboard](https://i.gyazo.com/e6449f4d16d7637164955d6e8f2dc0f1.png)

**Comment by BoGuu** [comment]
Could you confirm your version?

**Comment by llMysterioll** [comment]
.5 If your talking about the CyberByte version.

**Comment by llMysterioll** [comment]
Also just confirmed it works with Extdb 1, I used the same info just changed the database. But problem is im using Extdb 2

**Comment by Jason2605** [comment]
The extDB version would have no influence on the panel, please check your AltisLife version when you are receiving errors.

**Comment by llMysterioll** [comment]
Altis Life version is 4.4r4

**Comment by MightySCollins** [comment]
If you uncomment the [third line](https://github.com/Cyberbyte-Studios/CyberWorks/blob/master/index.php#L3) in `index.php` you should see errors displayed. Can paste the error?

**Comment by llMysterioll** [comment]
Notice: Trying to get property of non-object in C:\xampp\htdocs\CyberWorks-master\views\life\players.php on line 22
There is the error displaying on the players page.

**Comment by llMysterioll** [comment]
weirdly it shows the top ten players  on the dashboard with how much money the have.

**Comment by BoGuu** [comment]
Could you post a snapshot of your players table? Also, verify in the settings you're using 4.4R2+

**Comment by llMysterioll** [comment]
![PlayerTab](https://i.gyazo.com/6d29979dfefdd0b807e7dc51367a6def.png)
![Settings](https://i.gyazo.com/83e9e5e201cb9c62d552778131361a06.png)

**Comment by ghost** [comment]
Also having this issue with CyberWorks on 4.4r4

**Comment by BoGuu** [comment]
@llMysterioll 

Your database table

> Also, verify in the settings you're using 4.4R2+

**Comment by ghost** [comment]
@BoGuu here is mine on 4.4r4 if it matters, same error as him. http://i.imgur.com/qKM5WFG.png

**Comment by ghost** [comment]
here is the exported table (if that's what you meant) http://www.filedropper.com/showdownload.php/players_4

**Comment by ghost** [comment]
Fixes players tab being broken in Altis Life 4.4r3 +

The database players table is no longer playerid but instead pid. I replaced all counts of this.

So replace playerid with pid.

pastebin: http://pastebin.com/Gv2JGYi4

**Comment by llMysterioll** [comment]
@jrm100 It worked ,thanks :) !

**Comment by ghost** [comment]
@llMysterioll np, if you want to fix the error in gang tab do the same in adminpanel/gfunctions.php - idk how to fix houses though.

**Comment by ghost** [comment]
@llMysterioll heres a fixed dashboard.php 
http://pastebin.com/JpcPRXTR

**Comment by llMysterioll** [comment]
@jrm100 Yeah i've been going through the other things and fixing the different pages.

**Comment by BoGuu** [comment]
The reason why the panel isn't working for you, is because you're not using 4.4R4 (or before), you're using the dev build, which is not yet supported. Even if we added changes for it, I could change any of the DB structure at any point in time still. Closed for now
