### ISSUE TITLE
Variable

### ISSUE THREAD

**Issue by deanm1990** [Cyberbyte-Studios/CyberWorks#66]
Hi

How would i change variables

My database isnt quite as standard as the simple Altis Life, and my medic levels etc have different varialbe names. therefor when i update the levels via the panel, it doesnt actually update it on the database.

please advise

**Comment by BoGuu** [comment]
https://github.com/Cyberbyte-Studios/CyberWorks/search?utf8=✓&q=mediclevel&type=Code

**Comment by deanm1990** [comment]
Thankyou for the quick response, changed it all- however, i see the panel working fine. The only thing i can still change is just licenses . I can't edit medic levels or cop levels. It has no effect on the actual DB - any advice ?

**Comment by BoGuu** [comment]
Mission version?

**Comment by MightySCollins** [comment]
Chances are you have made a small mistake when editing the queries. Can you send me a small sample of your data to support@cyberbyte.org.uk and the version which you have edited so I can look into it further.

**Comment by Jason2605** [comment]
Stale
