### ISSUE TITLE
Edit databases don't work

### ISSUE THREAD

**Issue by AsboniaTV** [Cyberbyte-Studios/CyberWorks#69]
After opening "Edit Databases", and click edit on which one I want to edit, the page opens BLANK

![](https://i.gyazo.com/a44f605e2897305999ec0cb9f2ff318f.png)

**Comment by AsboniaTV** [comment]
also players don't show up in 'game servers'

**Comment by MightySCollins** [comment]
What Altis Life version are you using? Also if you uncomment the third line in index.php are there any errors?

**Comment by AsboniaTV** [comment]
To be honest, I don't know. Its an A3L - My old community ran you guys with it with no errors. 
- Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in C:\xampp\htdocs\a3lpanel\views\life\dashboard.php on line 193 -

**Comment by MightySCollins** [comment]
Try switching the altis version setting to be an older version. We recently made breaking changes to support the latest framework.

**Comment by AsboniaTV** [comment]
Changed to 3.x.x.x
Error message is gone.
Tho neither player list nor editserver work?

**Comment by MightySCollins** [comment]
@Jason2605 You had a chance to look into this at all?

**Comment by Jason2605** [comment]
@MightySCollins Ive been away, sorry about that.

**Comment by Jason2605** [comment]
@jdhk94, Can you please find out what version of framework you are running off, or post a screenshot of your players database table.

**Comment by AsboniaTV** [comment]
Which framework?

**Comment by Jason2605** [comment]
Well, I'm guessing the A3L mission you are running is based of Tonics framework, so can you find out the version its using

**Comment by AsboniaTV** [comment]
3.x.x.x.x
https://gyazo.com/2989a298316c0ef82f76738f83afaeae

**Comment by Jason2605** [comment]
So upon switching the version to an older version, and the error uncommented, you are still receiving no errors, however still not working?

**Comment by AsboniaTV** [comment]
I dont see any errors no. Though I cant see any ingame players nor do I have the ability to delete a server I added on it.

**Comment by Jason2605** [comment]
Are any of the other pages working as they should?

**Comment by AsboniaTV** [comment]
Players & Vehicles & Houses are working fine

**Comment by MightySCollins** [comment]
I cannot seem to replicate this issue. Can you send me an email at support@cyberbyte.org.uk with a small sample of data from your database so I can investigate further.
