### ISSUE TITLE
Player, Vehice, House Overview didn't work!

### ISSUE THREAD

**Issue by eLHavanna** [Cyberbyte-Studios/CyberWorks#70]
Hey Cyberbyte Studios/Community,

In the Picture your see the Problem:
![ss](https://cloud.githubusercontent.com/assets/24394832/20897036/acc609f6-bb20-11e6-96d7-2791d174c365.PNG)

We are using the Arma 3 Altis Version: 4.5

**Comment by schasching** [comment]
I have the same problem.

**Comment by MightySCollins** [comment]
@eLHavanna any chance you can send an email to support@cyberbyte.org.uk with a small sample of your database?

**Comment by eLHavanna** [comment]
Okay "Players" is Working, but not Vehicle and Houses! And the Player Search Funktion is not Working!

**Comment by schasching** [comment]
Yes me too.
^^

**Comment by MightySCollins** [comment]
I can look into fixing it but I will need some sample of data to dev against. I do not have a copy of any schema for the newer versions of Altis Life. If someone can email me some that would be great.

**Comment by eLHavanna** [comment]
What Datas your need? May i can send it you!

**Comment by MightySCollins** [comment]
Send an email to support@cyberbyte.org.uk with a MySQLDump of a database. If you want you can remove any personal data and change names etc, as long as its something I can insert into a database to use CyberWorks.

**Comment by eLHavanna** [comment]
Okay in ca. 10min i send it to the email!

**Comment by eLHavanna** [comment]
Email is out! I hope your find something! Thanks a lot for your help.

**Comment by MightySCollins** [comment]
This might have been fixed in d017181d0a57b54d5824982111a91a9d4bd73d34

**Comment by eLHavanna** [comment]
Yeah is fixed! Much Thanks to Cyberbyte!
