### ISSUE TITLE
View in Players --> Vehicle

### ISSUE THREAD

**Issue by schasching** [Cyberbyte-Studios/CyberWorks#73]
If a player has more Vehicle i dont can show all vehicle what he has. 
If i press more i always get No Vehicle.

**Comment by MightySCollins** [comment]
You can try searching in the vehicles page. But it should show them on the more button...

**Comment by Budji** [comment]
We're having the same issue on our server.
Just getting the "No vehicles" when clicking the more button, any fixes for that @MightySCollins ?
