### ISSUE TITLE
Players,Houses,Cars, etc. showing cannot be found - Checked other issues for fixes, didn't work

### ISSUE THREAD

**Issue by stjeebee** [Cyberbyte-Studios/CyberWorks#76]
Hello once again, lol. 

So I had an issue and it was fixed by these wonderful people. But, now I'm getting a 'player cannot be found' and equivalent across the players, houses, and cars. I saw the fix given before but I checked and what they suggested is actually changed in the files I have. We use AltisLife 3.4.8 (ancient, right?) and I'm unsure how to move forward. 

Thanks,

Nick

**Comment by Jason2605** [comment]
Are you getting any errors throughout the logs? Have you also tried turning the error reporting on (mentioned by Sam before) and seeing what is produced, that would help narrow down the issue.

**Comment by Jason2605** [comment]
Please see latest push, and switch your version to 3.x.x.x, please reopen if you are still having issues.
