### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by ItsSpirit** [Cyberbyte-Studios/CyberWorks#79]
Using Cyberworks 0.5.0 everything works well except licenses when adding licenses it doesn't update the database and after refreshing the page the green highlight goes back to grey

After turning on the error messages by removing the // in front of error_reporting(E_ALL); // Turn on for error messages it doesn't seem to give any errors the only errors that pop up are;

Notice: Undefined index: player_arrest in C:\xampp\htdocs\CyberWorks\views\life\editPlayer.php on line 59

Notice: Undefined index: player_blacklist in C:\xampp\htdocs\CyberWorks\views\life\editPlayer.php on line 60

The licenses in the database look like "[[``license_civ_MDMA``,0],[``license_civ_meth``,0],[``license_civ_coke``,0],[``license_civ_driver``,0],[``license_civ_air``,1],[``license_civ_heroin``,0],[``license_civ_marijuana``,0],[``license_civ_gang``,0],[``license_civ_boat``,0],[``license_civ_oil``,0],[``license_civ_dive``,0],[``license_civ_truck``,0],[``license_civ_gun``,0],[``license_civ_rebel``,0],[``license_civ_diamond``,0],[``license_civ_copper``,0],[``license_civ_iron``,0],[``license_civ_sand``,0],[``license_civ_salt``,0],[``license_civ_cement``,0],[``license_civ_home``,0],[``license_civ_rifle``,0]]"

and the column name is civ_licenses

**Comment by MightySCollins** [comment]
Did you manage to fix this?

**Comment by Jason2605** [comment]
Was this an issue unique to you or an issue with the panel, and like Sam says did you manage to solve it yourself?
