### ISSUE TITLE
Can't change level + money

### ISSUE THREAD

**Issue by NiiRoZz** [Cyberbyte-Studios/CyberWorks#80]
Hello,

I have 5.0 version of altis life,

when i want to change any level or cash, send me a message " Edited xxxxxxx "
But when i refresh the page it doesn't work, i have saw a difference,
[Image](https://gyazo.com/b6fa7f43f7a4b1deebc374a6b014fe1f)
This menu are ok, all my ranks are good but when i click on edit : 
[Image](https://gyazo.com/d3d3e99e38e8714c0847be888f5b7252)
My medic rank are not good, and i can't edit anything with succes.

Thanks for reading this.

**Comment by MightySCollins** [comment]
What version of AltisLife are you using?

**Comment by NiiRoZz** [comment]
Version 5.0.0

**Comment by Jason2605** [comment]
I have a 5.0 server running CyberWorks running with the latest version (not the from the releases tab) and it edits fine, please can you provide some more information?

**Comment by NiiRoZz** [comment]
@Jason2605 Ok, i will test to reinstall another time, and if don't work i will give you more information

**Comment by BoGuu** [comment]
@NiiRoZz 

What version of AL are you set to in the settings page?

**Comment by NiiRoZz** [comment]
@BoGuu 5.0 version, if i change this version i can't see any players.

**Comment by NiiRoZz** [comment]
I have found a problem i think, i had fresh install, it's work, but when i modify any option, like max player cop level to 12, i submit my changes and i can't edit any player after that . 

Another trouble, when i had install the server i have choose 5.0 but when i go to option i have preselected 4.4r2.

@Jason2605 @MightySCollins

**Comment by BoGuu** [comment]
@NiiRoZz 

Can you try with 90e1728?

**Comment by NiiRoZz** [comment]
With all your last change @BoGuu and @Jason2605 All works, thanks for your reply and your fixes.

Cordially NiiRoZz
