### ISSUE TITLE
Getting some Errors on my Webspace.

### ISSUE THREAD

**Issue by BeFreezy** [Cyberbyte-Studios/CyberWorks#95]
Hey ya'll, just ran into some issues.

I can open most of the url's just fine except a few of them, here are some errors I catched.

`[06-Feb-2018 19:05:00 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to a member function query() on null in /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/views/templates/scripts.php:126
Stack trace:
#0 /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/views/templates/template.php(203): include()
#1 /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/index.php(564): include('/home/webpages/...')
#2 {main}
thrown in /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/views/templates/scripts.php on line 126
[06-Feb-2018 19:05:00 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to a member function query() on null in /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/views/templates/scripts.php:126
Stack trace:
#0 /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/views/templates/template.php(203): include()
#1 /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/index.php(564): include('/home/webpages/...')
#2 {main}
thrown in /home/webpages/lima-city/befreezy2/CyberWorks-0.5.3/views/templates/scripts.php on line 126`

**Comment by MightySCollins** [comment]
We recommend you use our new version which can be found at https://github.com/Cyberbyte-Studios/CyberWorks-3

**Comment by BeFreezy** [comment]
oh, didn't even know you had a newer version, thanks!

#close
